export function renderMcpServer({ title, version, baseUrl, ops }) {
  const tools = ops.map(({ name, description, method, path, paramLocs, inputSchema }) => ({
    name,
    description,
    method,
    path,
    paramLocs,
    inputSchema,
  }));

  return `#!/usr/bin/env node
// Generated by keymaker — MCP server for ${title}
// Run: node mcp-server.mjs   (stdio transport; point any MCP client at it)
// Env: API_BASE_URL (default ${baseUrl}), API_KEY (sent as Bearer token)
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { ListToolsRequestSchema, CallToolRequestSchema } from "@modelcontextprotocol/sdk/types.js";

const BASE_URL = (process.env.API_BASE_URL ?? ${JSON.stringify(baseUrl)}).replace(/\\/$/, "");
const API_KEY = process.env.API_KEY ?? "";

const TOOLS = ${JSON.stringify(tools, null, 2)};

const server = new Server(
  { name: ${JSON.stringify(`${title} (agent-ready)`)}, version: ${JSON.stringify(version)} },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: TOOLS.map(({ name, description, inputSchema }) => ({ name, description, inputSchema })),
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const tool = TOOLS.find((t) => t.name === request.params.name);
  if (!tool) {
    return { content: [{ type: "text", text: \`Unknown tool: \${request.params.name}\` }], isError: true };
  }
  const args = request.params.arguments ?? {};
  let path = tool.path;
  const query = new URLSearchParams();
  const headers = { "content-type": "application/json" };
  if (API_KEY) headers.authorization = \`Bearer \${API_KEY}\`;
  const body = {};
  let hasBody = false;
  for (const [key, value] of Object.entries(args)) {
    if (value === undefined || value === null) continue;
    const loc = tool.paramLocs[key];
    if (loc === "path") path = path.replace(\`{\${key}}\`, encodeURIComponent(String(value)));
    else if (loc === "query") query.set(key, String(value));
    else if (loc === "header") headers[key.toLowerCase()] = String(value);
    else {
      if (key === "body" && typeof value === "object") Object.assign(body, value);
      else body[key] = value;
      hasBody = true;
    }
  }
  const url = \`\${BASE_URL}\${path}\${[...query].length ? \`?\${query}\` : ""}\`;
  try {
    const res = await fetch(url, {
      method: tool.method,
      headers,
      ...(hasBody ? { body: JSON.stringify(body) } : {}),
    });
    const text = await res.text();
    return {
      content: [{ type: "text", text: \`HTTP \${res.status} \${tool.method} \${url}\\n\${text.slice(0, 20000)}\` }],
      isError: res.status >= 400,
    };
  } catch (err) {
    return { content: [{ type: "text", text: \`Request failed: \${err.message}\` }], isError: true };
  }
});

const transport = new StdioServerTransport();
await server.connect(transport);
console.error(\`[keymaker] MCP server ready — \${TOOLS.length} tools proxying \${BASE_URL}\`);
`;
}
