export function renderAuthMd({ spec, serviceUrl }) {
  const title = spec.info?.title ?? "API";
  return `# Agent registration — ${title}

> Machine-readable instructions for AI agents to register and obtain scoped API keys with no human in the loop. Generated by keymaker. Pattern-compatible with auth.md (https://workos.com/auth-md); served at /auth.md and /.well-known/auth.md.

## Register

\`\`\`
POST ${serviceUrl}/agent-auth
Content-Type: application/json

{
  "client_name": "<your agent's name>",
  "scopes": ["read"],
  "attestation": "<optional: ID-JAG token from your agent platform>"
}
\`\`\`

Response \`201\`:

\`\`\`json
{
  "key_id": "key_…",
  "api_key": "ak_…",
  "status": "unclaimed | agent_verified",
  "scopes": ["read"],
  "expires_at": "<ISO timestamp or null>",
  "claim_token": "ct_…",
  "claim_url": "…"
}
\`\`\`

- **With a valid platform attestation** the key is issued as \`agent_verified\` and does not expire.
- **Without one** the key is temporary (60 minutes) — enough to try the API — and becomes permanent when a human claims it:

\`\`\`
POST ${serviceUrl}/agent-auth/claim
{ "claim_token": "ct_…" }
\`\`\`

Use the key as \`Authorization: Bearer ak_…\` on every API request.

## Scopes

- \`read\` — non-mutating endpoints (GET)
- \`write\` — mutating endpoints (POST/PUT/PATCH/DELETE)

## For the API's backend (verification + metering)

\`\`\`
POST ${serviceUrl}/agent-auth/verify
{ "api_key": "ak_…" }
\`\`\`

Returns \`{ "valid": true, "scopes": […], "status": "…", "usage": <request count> }\` and increments the usage meter. \`401\` if unknown or expired.

## Discovering this API

- [llms.txt](${serviceUrl}/llms.txt) — agent-readable API overview
- MCP server available (stdio): ask the vendor for connection details, or run the generated \`mcp-server.mjs\`
`;
}
